butter_and_batter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, landing_page, add_product_entry_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('show-main/', show_main, name='show_main'),
    path('create-product-entry/', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-product-entry-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet">
        {% block meta %} {% endblock meta %}
        <link rel="stylesheet" href="{% static 'css/global.css' %}"/>

        <style>
            body {
                font-family: 'Poppins', sans-serif;
            }
        </style>

        <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    </head>

    <nav class="border-gray-300 border-b font-poppins">
        <div class="mx-auto py-4 px-4">
            <div class="flex justify-between">
                <a href="/" class="flex items-center">
                    Butter&Batter
                </a>

                <!-- hamburger -->
                <div class="md:hidden justify-between">
                    <ion-icon name="menu-outline" class="text-3xl cursor-pointer "></ion-icon>
                </div>

                <!-- desktop view -->
                <ul class="hidden md:flex items-center md:space-x-4 md:pr-3">
                    <a href="/" class="hover:text-red-900"><li>home</li></a>
                    <a href="#" class="hover:text-red-900"><li>about</li></a>
                    <a href="/" class="hover:text-red-900"><li>pastries</li></a>
                    {% if user.is_authenticated %}
                    <span class="text-yellow-900">hi, {{ user.username }}</span>
                    <a href="{% url 'main:logout' %}" class="text-center bg-red-900 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                        logout
                    </a>
                    {% else %}
                    <a href="{% url 'main:login' %}" class="">
                      login
                    </a>
                    {% endif %}
                </ul>

            </div>
        </div>

        <!-- mobile view-->
        <div class="mobile-menu hidden md:hidden  px-4 w-full md:max-w-full">
            <div class="pt-2 pb-4 space-y-1">
                <ul class="">
                    <a href="/" class="hover:text-red-900"><li>home</li></a>
                    <a href="#" class="hover:text-red-900"><li>about</li></a>
                    <a href="/" class="hover:text-red-900"><li>pastries</li></a>
                </ul>
                {% if user.is_authenticated %}
                <span class="block text-yellow-950 pt-1 pb-4">hi, {{ user.username }}</span>
                <a href="{% url 'main:logout' %}" class="block text-center bg-red-900 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
                    Logout
                </a>
                {% else %}
                <a href="{% url 'main:login' %}" class="hover:text-gray-500">
                    login
                </a>
                {% endif %}
            </div>
        </div>

        <script>
            const menu = document.querySelector('.mobile-menu');
            const hamburger = document.querySelector('ion-icon');

            hamburger.addEventListener('click', () => {
                hamburger.name = hamburger.name === 'menu-outline' ? 'close' : 'menu-outline';
                menu.classList.toggle('hidden');
            });
          </script>
    </nav>

  <body class="bg-orange-50">
    {% block content %} {% endblock content %}
    

    <footer>
        <div class="border-t-2 bottom-0 px-4 justify-between w-full bottom-0  flex flex-row py-4 ">
            <p>Patricia Herningtyas</p>
            <p>PBP A</p>
        </div>
    </footer>

  </body>

</html>