butter_and_batter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_main, create_product_entry, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_product, delete_product, landing_page, add_product_entry_ajax, create_product_flutter

app_name = 'main'

urlpatterns = [
    path('', landing_page, name='landing_page'),
    path('show-main/', show_main, name='show_main'),
    path('create-product-entry/', create_product_entry, name='create_product_entry'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-product-entry-ajax', add_product_entry_ajax, name='add_product_entry_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User

class ProductEntry(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import ProductEntry
from django.utils.html import strip_tags

class ProductEntryForm(ModelForm):
    class Meta:
        model = ProductEntry
        fields = ["name", "price", "description"]

    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

main/views.py
from django.shortcuts import render, redirect, reverse
from main.forms import ProductEntryForm
from main.models import ProductEntry
from django.http import HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
import datetime
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags
import json
from django.http import JsonResponse



def landing_page(request):
    return render(request, 'landing_page.html')

@login_required(login_url='/login')
def show_main(request):

    context = {
        'nama': request.user.username,
        'kelas': "PBP-A",
        'tagline': "Your Daily Dose of Sweetness",
        'description': "Welcome to Butter & Batter — where every bite is a blissful journey of flavors.",
        # 'last_login': request.COOKIES['last_login'],

    }

    return render(request, 'main.html', context)


def create_product_entry(request):
    form = ProductEntryForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.user = request.user
        product_entry.save()
        return redirect('main:show_main')

    context = {
        'form': form,
    }
    return render(request, "create_product_entry.html", context)

def show_xml(request):
    data = ProductEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type='application/xml')

def show_json(request):
    data = ProductEntry.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type='application/json')

def show_xml_by_id(request, id):
    data = ProductEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = ProductEntry.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been successfully created!")
            return redirect("main:login")
    context = {'form': form}
    return render(request, "register.html", context)

def login_user(request):
   if request.method == 'POST':
      form = AuthenticationForm(data=request.POST)

      if form.is_valid():
        user = form.get_user()
        login(request, user)
        response = HttpResponseRedirect(reverse("main:show_main"))
        response.set_cookie('last_login', str(datetime.datetime.now()))
        return response
      else:
        messages.error(request, "Invalid username or password. Please try again.")

   else:
      form = AuthenticationForm(request)
   context = {'form': form}
   return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get the product entry
    product = ProductEntry.objects.get(pk=id)

    # Set product entry sebagai instance dari form
    form = ProductEntryForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save() # simpan form dan kembali ke halaman awal
        return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = ProductEntry.objects.get(pk=id) # Get product berdasarkan id
    product.delete() # hapus product
    return HttpResponseRedirect(reverse('main:show_main'))

@csrf_exempt
@require_POST
def add_product_entry_ajax(request):
    form = ProductEntryForm(request.POST)
    
    if form.is_valid():
        product = form.save(commit=False)  # Save the product without committing yet
        product.user = request.user  # Set the user manually
        product.save()  # Now save it
        return HttpResponse("CREATED", status=201)
    else:
        # Send back an error message with status 400
        error_message = ', '.join([f"{field}: {error[0]}" for field, error in form.errors.items()])
        return HttpResponse(f"Error: {error_message}", status=400)
    
@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_product = ProductEntry.objects.create(
            user=request.user,
            name=data["name"],
            description=data["description"],
            price=int(data["price"])
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

main/templates/create_product_entry.html
{% extends 'base.html' %}

{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto bg-orange-200 p-6 rounded-lg shadow-lg my-4">
    <h1 class="text-2xl text-yellow-950 font-semibold mb-6">Add New Pastry!</h1>

    <form method="POST">
        {% csrf_token %}
        <!-- {{ form | crispy}} -->
        <div class="space-y-4">
            {% for field in form %}
            <div class="flex flex-col">
                <label for="{{ field.id_for_label }}" class="text-lg font-medium text-gray-700 mb-1">{{ field.label }}</label>
                <div class="relative">
                    {{ field }}
                    {% if field.errors %}
                    <span class="absolute text-red-500 text-sm">{{ field.errors }}</span>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="mt-6 text-right">
            <input type="submit" value="Add Pastry" class="bg-red-900 hover:bg-red-950 text-white py-2 px-4 rounded transition duration-200"/>
        </div>
    </form>
</div>
{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% load static %}

{% block content %}
<div class="min-h-screen flex items-center justify-center">
    <div class="bg-orange-200 p-8 rounded-lg shadow-lg w-full max-w-lg">
        <h1 class="text-3xl font-bold mb-6 text-center text-yellow-950">Edit Menu</h1>

        <form method="POST" class="space-y-6">
            {% csrf_token %}

            <div>
                <!-- Render the form using the crispy filter, which will apply styles based on the crispy settings -->
                {{ form | crispy }}
            </div>
            
            <div class="flex justify-end">
                <input type="submit" value="Edit Menu" class="bg-yellow-900 hover:bg-red-950 text-white font-bold py-2 px-4 rounded-lg cursor-pointer shadow-md focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"/>
            </div>
        </form>
    </div>
</div>
{% endblock %}

main/templates/landing_page.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Butter & Batter</title>
    <!-- Tailwind CSS CDN -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

</head>
<body class="bg-orange-50 font-poppins">
    {% extends 'base.html' %}
    {% load static %}
    {% block content %}

    <!-- mobile view-->
    <div class="flex flex-col items-center md:hidden min-h-screen">
        <h1 class="text-4xl font-extrabold pt-16 px-10 text-center text-yellow-950">Crafted with Love, Baked with Butter & Batter.</h1>
        <div class="pt-14 pb-14">
            <img src="{% static 'image/bakery.png' %}" alt="croissant" class="w-[300px]">
        </div>
        <a href="{% url 'main:show_main' %}" class="block">
            <button class="bg-yellow-900 text-white font-semibold py-2 px-4 rounded-lg shadow-md hover:bg-red-900 flex flex-row justify-center items-center w-full">
                Order Now
                <ion-icon name="arrow-forward-outline" class="text-xl pl-2"></ion-icon>
            </button>
        </a>
    </div>

    <!-- desktop view-->
    <div class="hidden md:flex md:flex-row md:items-center md:justify-center md:items-center min-h-screen">
        <div class="flex-col ml-32 mr-12">
        <h1 class="text-4xl font-extrabold w-64 pt-10 pb-4 text-left text-yellow-950">Crafted with Love, Baked with Butter & Batter.</h1>
        <div class="bg-yellow-900 w-64 text-white font-semibold py-2 rounded-lg shadow-md hover:bg-red-900 flex flex-row justify-center items-center">
            <a href="{% url 'main:show_main' %}" class="">
                Order Now
            </a>
            <ion-icon name="arrow-forward-outline" class="text-xl pl-2"></ion-icon>
        </div>
        </div>
        <div class="pt-16 pb-14 pr-24">
            <img src="{% static 'image/bakery.png' %}" alt="croissant" class="w-[510px]">
        </div>
    </div>
    {% endblock content %}
</body>
</html>

main/templates/login.html
{% extends 'base.html' %}

{% load tailwind_filters %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center">
  <div class="bg-orange-200 p-8 rounded-lg shadow-lg w-full max-w-md mx-4">
    <h1 class="text-3xl font-bold mb-6 text-center text-yellow-950">Login</h1>

    <form method="POST" action="">
      {% csrf_token %}
      <div class="mb-4 ">
        {{ form | crispy }}
      </div>

      <div class="flex justify-center">
        <input
          class="btn bg-yellow-950 hover:bg-red-900 text-white font-semibold py-2 px-4 rounded w-full cursor-pointer"
          type="submit" value="Login" />
      </div>
    </form>

    {% if messages %}
    <ul class="mt-4">
      {% for message in messages %}
      <li class="text-green-800 text-sm">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <p class="text-center text-gray-600 mt-6">
      Don't have an account yet?
      <a href="{% url 'main:register' %}" class="text-blue-500 hover:underline">Register Now</a>
    </p>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %} 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Butter & Batter</title>
    <!-- Tailwind CSS CDN -->
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700&display=swap"
      rel="stylesheet"/>
    <link
      href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
      rel="stylesheet"/>
      {% block meta %}
      <script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
     {% endblock meta %}
  </head>
  <body
    class="bg-orange-50 leading-normal tracking-normal font-poppins min-h-screen mx-4">
    {% block content %}
    {% load static %}
    <div class="lg:max-w-4xl md:max-w-2xl max-w-lg bg-orange-200 p-8 rounded-lg shadow-lg mt-6 mb-8 mx-auto">
      <header class="text-center mb-8">
        <h1 class="font-poppins text-4xl font-bold text-yellow-950 mb-2">
          🧈{{ tagline }}🧈
        </h1>
        <p class="text-zinc-600">{{ description }}</p>
      </header>

      <section class="mb-8">
        <h2
          class="text-2xl text-center md:text-left text-yellow-950 font-semibold mb-4 border-b-2 border-white pb-2"
        >
          Our Delicious Offerings
        </h2>
      </section>

      <div id="product_entry_cards"></div>

        <div class="text-center mt-6">
          <a href="{% url 'main:create_product_entry' %}">
              <button class="btn text-white font-semibold py-2 px-4 rounded-lg shadow-md bg-yellow-900 hover:bg-red-950 mr-4 transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105 mb-4">
                Add New Pastry Entry
              </button>
          </a>
        
          <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-yellow-900 hover:bg-red-950 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();">
            Add New Product Entry by AJAX
          </button>
       
        </div>

        <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
            <div id="crudModalContent" class="relative bg-orange-200 rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
              <!-- Modal header -->
              <div class="flex items-center justify-between p-4 border-b rounded-t">
                <h3 class="text-xl font-semibold text-yellow-950">
                  Add New Product Entry
                </h3>
                <button type="button" class="text-gray-400 bg-transparent hover:bg-red-950  hover:text-white rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
                  <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                  </svg>
                  <span class="sr-only">Close modal</span>
                </button>
              </div>
              <!-- Modal body -->
              <div class="px-6 py-4 space-y-6 form-style">
                <form id="productEntryForm">
                  {% csrf_token %}
                  <div class="mb-4">
                    <label for="name" class="block text-sm font-medium text-yellow-950">Name</label>
                    <input type="text" id="name" name="name" class="mt-1 block w-full border border-orange-200 rounded-md p-2 hover:border-orange-900" placeholder="Enter your Pastry" required>

                  </div>
                  <div class="mb-4">
                    <label for="price" class="block text-sm font-medium text-yellow-950">Price</label>
                    <input type="number" id="price" name="price" min="1" class="mt-1 block w-full border border-orange-200 rounded-md p-2 hover:border-orange-900" required>
                  </div>
                  <div class="mb-4">
                    <label for="description" class="block text-sm font-medium text-yellow-950">Description</label>
                    <textarea id="description" name="description" rows="3" class="mt-1 block w-full h-52 resize-none border border-orange-200 rounded-md p-2 hover:border-orange-900" placeholder="Describe your Pastry" required></textarea>
                  </div>
                </form>
              </div>
              <!-- Modal footer -->
              <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
                <button type="button" class="bg-zinc-800 hover:bg-zinc-900 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
                <button type="submit" id="submitProductEntry" form="productEntryForm" class="bg-yellow-900 hover:bg-red-950 text-white font-bold py-2 px-4 rounded-lg">Save</button>
              </div>
            </div>
          </div>
    
    </div>
    <script>
      function addProductEntry() {
        fetch("{% url 'main:add_product_entry_ajax' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#productEntryForm')),
        })
        .then(response => {
          if (response.ok) {
            refreshProductEntries();
            document.getElementById("productEntryForm").reset();
            hideModal(); // Hide modal if successful
          } else {
            return response.text(); // Capture the error message
          }
        })
        .then(errorMessage => {
          if (errorMessage) {
            alert(errorMessage); // Show error message to the user
          }
        })
        .catch(error => {
          console.error("Error:", error);
        });

        return false;
      }

      // fungsi untuk mengambil data produk dari server lalu menampilkannya
      async function getProductEntries() {
        return fetch("{% url 'main:show_json' %}").then((res) => res.json())
      }

      async function refreshProductEntries() {
        document.getElementById("product_entry_cards").innerHTML = "";
        document.getElementById("product_entry_cards").className = "";
        const productEntries = await getProductEntries();
        let htmlString = "";
        let classNameString = "";

        if (productEntries.length === 0) {
          htmlString = `
                <img src="{% static 'image/croissant.png' %}" alt="Empty" class="mx-auto w-1/2">
                <p class="text-center text-zinc-600">Belum ada data pastry pada Butter & Batter.</p>
                `;
        } else {
          classNameString ="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6";
          productEntries.forEach((item) => {
            const name = DOMPurify.sanitize(item.fields.name);
            const description = DOMPurify.sanitize(item.fields.description);
            htmlString += `
                        <div class="">
                            <div class="bg-orange-50 p-4 rounded-lg shadow-md transition-shadow duration-300 mb-3 hover:hover-bounce-up transition duration-500 ease-in-out transform hover:-translate-y-1 hover:scale-105">
                                <h3 class="text-xl font-semibold text-yellow-950 mb-2">${name}</h3>
                                <p class="text-gray-600 mb-2">Price: ${item.fields.price}</p>
                                <p class="text-gray-500">${description}</p>
                                <div>
                                    <a href="/edit-product/${item.pk}" class="bg-yellow-900  text-white font-semibold py-2 px-4 rounded-lg shadow-md hover:bg-red-950 inline-block mt-4">
                                        Edit
                                    </a>
                                </div>
                                <div>
                                    <a href="/delete/${item.pk}" class="bg-red-900 text-white font-semibold py-2 px-4 rounded-lg shadow-md hover:bg-red-950 inline-block mt-4">
                                        Delete
                                    </a>
                                </div>
                            </div>
                        </div>
                    `;
          });
        }
        document.getElementById("product_entry_cards").className = classNameString;
        document.getElementById("product_entry_cards").innerHTML = htmlString;
      }
      refreshProductEntries();

      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

  function showModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modal.classList.remove('hidden'); 
      setTimeout(() => {
        modalContent.classList.remove('opacity-0', 'scale-95');
        modalContent.classList.add('opacity-100', 'scale-100');
      }, 50); 
  }

  function hideModal() {
      const modal = document.getElementById('crudModal');
      const modalContent = document.getElementById('crudModalContent');

      modalContent.classList.remove('opacity-100', 'scale-100');
      modalContent.classList.add('opacity-0', 'scale-95');

      setTimeout(() => {
        modal.classList.add('hidden');
      }, 150); 
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);
  document.getElementById("productEntryForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addProductEntry();
  })
    </script>
    {% endblock content %}
  </body>
</html>

main/templates/register.html
{% extends 'base.html' %}
{% load tailwind_filters %}


{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<div class="min-h-screen flex items-center justify-center">
  <div class="bg-orange-200 p-8 rounded-lg shadow-lg w-full max-w-md mx-3">
    <h1 class="text-3xl font-bold mb-6 text-center text-yellow-950">Register</h1>

    <form method="POST">
      {% csrf_token %}
      <div class="mb-4">
        {{ form | crispy }}
      </div>

      <div class="flex justify-center">
        <input
          class="btn bg-green-600 hover:bg-green-700 text-white font-semibold py-2 px-4 rounded w-full cursor-pointer"
          type="submit" name="submit" value="Register" />
      </div>
    </form>

    {% if messages %}
    <ul class="mt-4">
      {% for message in messages %}
      <li class="text-red-600 text-sm">{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}
  </div>
</div>
{% endblock content %}